#if !canImport(ObjectiveC)
import XCTest

extension AsyncTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AsyncTests = [
        ("testAsync", testAsync),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AsyncTests.__allTests__AsyncTests),
    ]
}
#endif
